service: pwa-ssr
runtime: nodejs8

automatic_scaling:
  max_idle_instances: 1

default_expiration: "0s"

handlers:
# Cache forever (thanks to fingerprinting)
- url: /static
  static_dir: build/public/static
  expiration: "365d"

# Special case caching
- url: /manifest.json
  static_files: build/public/manifest.json
  upload: build/public/manifest.json

- url: /robots.txt
  static_files: build/public/robots.txt
  upload: build/public/robots.txt
  expiration: "1d"

# - url: /index.html
#   static_files: build/index.html
#   upload: build/index.html

# - url: /service-worker.js
#   static_files: build/service-worker.js
#   upload: build/service-worker.js

# Catch all other files (long cache)
- url: /(.*\..+)$
  static_files: build/public/\1
  upload: build/public/.*$
  expiration: "7d"

# Application dynamic routes
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
