// AppBar / Nav Drawer
export const INCREMENT_LOADING_COUNT = 'INCREMENT_LOADING_COUNT'
export const DECREMENT_LOADING_COUNT = 'DECREMENT_LOADING_COUNT'
export const TOGGLE_THEME = 'TOGGLE_THEME'
export const SET_NAV_VALUE = 'SET_NAV_VALUE'

// Snackbars
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

// API Status
export const RECEIVE_API_STATUS = 'RECEIVE_API_STATUS'

export const RECEIVE_YEAR_EVENTS = 'RECEIVE_YEAR_EVENTS'
