// AppBar / Nav Drawer
export const INCREMENT_LOADING_COUNT = 'INCREMENT_LOADING_COUNT'
export const DECREMENT_LOADING_COUNT = 'DECREMENT_LOADING_COUNT'

export const TOGGLE_THEME = 'TOGGLE_THEME'

export const SET_NAV_VALUE = 'SET_NAV_VALUE'
